server:
port: 8082
spring:
  main:
    web-application-type: reactive
  application:
    name: heartrate-monitor-service
  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: guest
    password: guest

  jackson:
    serialization:
      write_dates_as_timestamps: false


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/