services:

  challenge-center:
    container_name: challenge
#    build: ../challenge-center
    image: cynthialiu0805/challenge-center
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.rabbitmq.host=rabbit-mq
    #      - spring.rabbitmq.virtual-host=/
    ports:
      - "9090:9090"
    depends_on:
      - eureka
      - rabbit-mq

  game-center:
    container_name: game
#    build: ../game-center
    image: cynthialiu0805/game-center
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.rabbitmq.host=rabbit-mq
    #      - spring.rabbitmq.virtual-host=/
    ports:
      - "8092:8092"
    depends_on:
      - eureka
      - rabbit-mq
      - user-opt
      - trail-center

  heartrate-monitor:
    container_name: heartrate
#    build: ../heartrate-monitor
    image: cynthialiu0805/heartrate-monitor
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.rabbitmq.host=rabbit-mq
    #      - spring.rabbitmq.virtual-host=/
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - rabbit-mq
  #      - biometric-srv

  trail-center:
    container_name: trail
#    build: ../trail-center
    image: cynthialiu0805/trail-center
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.rabbitmq.host=rabbit-mq
    #      - spring.rabbitmq.virtual-host=/
    ports:
      - "8091:8091"
    depends_on:
      - eureka
      - rabbit-mq

  user-opt:
    container_name: user
#    build: ../user-opt
    image: cynthialiu0805/user-opt
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.rabbitmq.host=rabbit-mq
    #      - spring.rabbitmq.virtual-host=/
    ports:
      - "8090:8090"
    depends_on:
      - eureka
      - rabbit-mq


  eureka:
    container_name: eureka
#    build: ../discovery-server
    image: cynthialiu0805/discovery-server
    environment:
      - eureka.instance.ipAddress="127.0.0.1"
    ports:
      - "8761:8761"

  rabbit-mq:
    container_name: rabbit-mq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"