server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    peer-node-connect-timeout-ms: 10000

spring:
  application:
    name: eureka-registry
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168
        - 10.0