server:
  port: 9090
spring:
  application:
    name: challenge-center
  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: guest
    password: guest

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
