server:
  port: 8762

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: spring-gateway
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168
        - 10.0
    gateway:
      routes:
        - id: heartrate-monitor-service
          uri: lb://heartrate-monitor-service
          predicates:
            - Path=/hrm/v1**